### ISSUE TITLE
Drug combination

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#137]
Bringing back drug combination.

**Comment by Farnazmdi** [comment]
The steps to get `d{# of cells}/d{parameter}`:

- [ ] 1. For a specific time point (say 60 hrs) calculate the number of cells (in G1 and in G2) for a range of the parameter (say alpha), keeping all the other parameters constant in their optimum.
- [ ] 2. Now, we could have the scatter plot of the number of cells in some phase, over a range of alphas. So now we fit a polynomial to it (to make it continuous).
- [ ] 3. Now we could calculate the derivative of the number of cells w.r.t. the parameter. 

@aarmey does it sound about right?

**Comment by aarmey** [comment]
Right, except you don't need to do anything with polynomials, you can get the derivative with differencing from `Calculus.finite_difference`.

https://github.com/JuliaMath/Calculus.jl
https://en.wikipedia.org/wiki/Central_differencing_scheme

**Comment by Farnazmdi** [comment]
Thanks

**Comment by Farnazmdi** [comment]
#151

**Comment by Farnazmdi** [comment]
if the rates are not completely correct:

- [ ] scenario 1: replace `gamma_1` --> `alpha` between G1_i and D1_i.

similarly, replace `gamma_2` --> `beta` between G2_i and D2_i.
see if it works.

- [ ] scenario 2: replace those as a new parameter.

**Comment by Farnazmdi** [comment]
The reason is:
![image](https://user-images.githubusercontent.com/34812750/74683587-4a26b000-517e-11ea-81da-8dbab6e1c255.png)
For all the times --doesn't matter within or after experiment time-- for small values of death rate in G1 (at least), the number of cells increase with increasing concentration.

**Comment by Farnazmdi** [comment]
scenario 1:
![image](https://user-images.githubusercontent.com/34812750/74693013-b5807a00-519e-11ea-9e22-587595b2c8ac.png)

Although the cost is 1021 and the results make sense, but the model doesn't do a good job of fitting for the first 4 concentrations.

This is the number of cells by increasing gamma1:
![image](https://user-images.githubusercontent.com/34812750/74692897-2f643380-519e-11ea-97f5-627fcdcf8390.png)
![tmp (2)](https://user-images.githubusercontent.com/34812750/74692966-836f1800-519e-11ea-8c55-6927a2364dc6.gif)

![sth](https://user-images.githubusercontent.com/34812750/74693259-dbf2e500-519f-11ea-85b3-7fe6da641894.png)

**Comment by Farnazmdi** [comment]
second scenario:
the cell # over a range of gamma1:
![image](https://user-images.githubusercontent.com/34812750/74789695-5851fa80-526a-11ea-9c8d-16093c55cef6.png)

The cost is 491 which is significantly lower. It looks good, but doesn't fit that well.
![image](https://user-images.githubusercontent.com/34812750/74789767-8afbf300-526a-11ea-9153-388a2fdebde1.png)

Other results make sense.

The reason I am suggesting this change, is that the rate we use inwards to the death phase, is the same as death progression rate, as outward death rate. But in the paper -- and in our other phase transitions -- the outward should be different. 
The third scenario I guess makes more sense. To replace the only last transition in the death phase to be a new parameter.

**Comment by Farnazmdi** [comment]
Question: Does it make sense to have some kind of correlation between the rates? What is seems like here is that in the same concentration where we see jumps in alpha and beta, something happens in the gamma1 and gamma2.

**Comment by aarmey** [comment]
Isn’t that what the Hill relationship does, in effect?

**Comment by Farnazmdi** [comment]
Yes! Thanks.
Does the second scenario make sense to you? I mean having a different rate into the death phases, than the progression rate inside the death phases.

**Comment by Farnazmdi** [comment]
I guess we could assume the new parameter as inflow rate.

**Comment by aarmey** [comment]
I think your death rate idea is reasonable.

**Comment by Farnazmdi** [comment]
Are these plots what we are looking for, for the drug combinations? @aarmey 
![image](https://user-images.githubusercontent.com/34812750/75618780-dbefcf00-5b27-11ea-9af4-a4d8884de305.png)

![image](https://user-images.githubusercontent.com/34812750/75618787-f1fd8f80-5b27-11ea-8ece-44a32a9f5265.png)

![image](https://user-images.githubusercontent.com/34812750/75618795-017cd880-5b28-11ea-8c84-7479a6ecc07a.png)

**Comment by aarmey** [comment]
Something like this but not 3D would be good. How about the concentration of drug B on the x-axis, then two lines—one with no drug A and one at the IC50 of drug A.

**Comment by Farnazmdi** [comment]
We add the death rate in G1 and death rates in G2 to get the total death rate for a cell. I am forgetting something; are we also doing the Bliss combination for death rates of the drugs? Because sometimes their sum is greater than 1. Should I normalize them? @aarmey

**Comment by Farnazmdi** [comment]
Also, progression rates could be greater than 1, too. I guess I could limit the upper bound, but I'm not sure how this affects the fitting accuracy, and it just applies to progression rates, not the summation of death rates.

**Comment by aarmey** [comment]
I think we should just look at predictions for # of cells first, before some more elegant analysis.

**Comment by Farnazmdi** [comment]
Sorry, you mean I do the Bliss and look at the cell # predictions? Or just add them to get the parameters for combinations?

**Comment by aarmey** [comment]
No Bliss, just plotting cell #.

**Comment by Farnazmdi** [comment]
Sorry, with which parameter sets? I already have cell # for separate drugs.

**Comment by aarmey** [comment]
Oh sorry, I think I see what you're asking. The death progression rates should be combined by just adding them. alpha and beta, because they decrease from the effect of drug, should be combined through Bliss additivity. (Bliss additivity takes into account the fact that the drug effect is saturable—e.g., you can't get a negative alpha.)

**Comment by Farnazmdi** [comment]
Thanks, the problem is they could be greater than 1, not being negative. I guess Bliss has this assumption that individual effects are not greater than 1.

**Comment by aarmey** [comment]
In other words when a drug causes alpha to increase. This is fine—your Bliss effect will be negative but that's allowed.

**Comment by Farnazmdi** [comment]
Thank you.

**Comment by Farnazmdi** [comment]
![od](https://user-images.githubusercontent.com/34812750/75798728-d8c53080-5d2b-11ea-8c56-c2ab56f5ad75.png)
![par](https://user-images.githubusercontent.com/34812750/75798738-dbc02100-5d2b-11ea-8319-adb09860c304.png)

**Comment by aarmey** [comment]
Plot cell # vs. drug concentration, just at 96 hrs.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75823358-76cdf080-5d56-11ea-9602-ec0ddde44aa2.png)

**Comment by Farnazmdi** [comment]
#173

**Comment by aarmey** [comment]
Right plot. Doesn't look like those two drugs are all that helpful together...

**Comment by aarmey** [comment]
Could help to add more points in the plot so the curves are more smoothly defined.

**Comment by Farnazmdi** [comment]
Sorry I missed this. Sure, I will add more points in it right after finishing the `labelledArray` branch.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75909537-2069bc00-5e01-11ea-904e-bce7d6d0128e.png)
with 50 points

**Comment by aarmey** [comment]
Might want to just try all combinations of drugs.

**Comment by Farnazmdi** [comment]
If we are looking for those combinations that at high concentrations, the difference between individual drug and the combination is high, I can write a function to loop over all combinations and find the one with maximum difference in the cell #. Is this helpful? Because now I have 50 concentrations, if we want to look at the combination for all of them, it is going to be 2500 plots :))

**Comment by aarmey** [comment]
I think better would be to just make a notebook with plots for all combinations. I don't really have a good idea of what the output would be, and interesting behavior in either direction (more effective or not) would be good to see.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75926353-40a87380-5e1f-11ea-8ac3-89ca80c826ac.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75926915-2e7b0500-5e20-11ea-8fee-d23113bdae14.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75927037-6da95600-5e20-11ea-867e-2aacfa78874c.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75927141-a34e3f00-5e20-11ea-9ed1-76b6de49d9e4.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75927960-4489c500-5e22-11ea-8927-a1170117f7b3.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75928157-a813f280-5e22-11ea-8a05-784d451002cf.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75928339-09d45c80-5e23-11ea-8a05-5278281b46cd.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75928460-4c963480-5e23-11ea-8b72-1d534e26af4d.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75928849-2624c900-5e24-11ea-9fa7-eb324684aec1.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/75929009-7dc33480-5e24-11ea-9d77-f998f33ef9e5.png)
This one is weird, the parameter (G2 progression rate) becomes negative, and from some concentration the cell # becomes negative...

**Comment by Farnazmdi** [comment]
Please let me know if we are looking for another kind of combination plots. @aarmey

**Comment by aarmey** [comment]
How do you get negative cell numbers? That should never happen...

**Comment by Farnazmdi** [comment]
I guess it comes from the fact that we let the Bliss combination parameters to be negative. First, this assertion breaks:
![image](https://user-images.githubusercontent.com/34812750/75929361-46a15300-5e25-11ea-893c-bbc4c48e494b.png)
If I comment out this assertion, then this breaks:
![image](https://user-images.githubusercontent.com/34812750/75929496-92ec9300-5e25-11ea-92c2-b14dbbaed63d.png)

**Comment by Farnazmdi** [comment]
I could say, when the cell # became negative, just set it to zero.

**Comment by aarmey** [comment]
No, because it likely indicates an underlying problem. Bliss should never give you a negative number. Can you check your code?

**Comment by Farnazmdi** [comment]
Even if the values are greater than 1?

**Comment by Farnazmdi** [comment]
> The death progression rates should be combined by just adding them. alpha and beta, because they decrease from the effect of drug, should be combined through Bliss additivity. (Bliss additivity takes into account the fact that the drug effect is saturable—e.g., you can't get a negative alpha.)

I mean, in gemcitabine, the beta is increasing, so maybe this makes them not qualified to use Bliss...

**Comment by Farnazmdi** [comment]
For just gemcitabine, I will restrict the `max_beta` to be 1. I guess this will resolve the problem.

**Comment by aarmey** [comment]
But if beta increases, that shouldn't lead to beta becoming negative in the additive combination. It should lead to beta in the combination being larger...

**Comment by aarmey** [comment]
If you have a drug A that increases a quantity by 10% (so 1.1 with drug), and a drug B that halves that quantity (so 0.5), the Bliss additive quantity with both present should be somewhere between 0.5 and 0.6, not negative.

**Comment by Farnazmdi** [comment]
[this](https://github.com/meyer-lab/DrugResponseModel.jl/blob/13e3eb59c0e454bb9c03922fbd79d1119345ca59/src/allDrugs.jl#L161) is my Bliss combination. The way I thought about it was, let's say for some concentration of drug A we have `beta = 1.6` and for drug B we have `beta = 3.0`. Based on this formula, the combined effect would be: `4.6 - 4.8 = -0.2 ` 
these are the gemcitabine and 
![image](https://user-images.githubusercontent.com/34812750/75937456-c33e2c80-5e39-11ea-92ab-1759485e586c.png)

**Comment by aarmey** [comment]
Before plugging into Bliss, the parameter effects have to be converted into units of fractional decrease. For example, if drug A decreases beta from 1.0 to 0.9, then the value for the drug A effect should be 0.1. If drug B decreases beta from 1.0 to 0.5, then the value plugged into Bliss is 0.5. After plugging the values into Bliss, you then have to convert back to units of beta. For example, Bliss *can* give you a negative value, which would correspond to beta increasing. But, this *does not* mean that beta is negative.

**Comment by Farnazmdi** [comment]
Just to confirm I understood it correctly:
1. subtract the first (control) parameter from other concentration parameters (converted into units of fractional decrease)
2. Input these to Bliss
3. add the control back to the combined values (?)
Could you please elaborate on converting them back? I mean since it is a combination, I don't know that I should use drug A or drug B as the base unit of the parameters.

**Comment by aarmey** [comment]
Re 1, you need to subtract the control and flip the values, since a decrease is a positive drug effect. Re 3, I just mean using the control to convert back to the original quantity units.

You should write a few tests to check that the function you have does this properly (e.g., my example above).

**Comment by Farnazmdi** [comment]
#178
