### ISSUE TITLE
version conflict? the examples not working

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#15]
`type FPFunctional Cache has no field caches` the error for the previous examples.

**Comment by Farnazmdi** [comment]
Yes, maybe I have to revert the version of packages I am using because I updated them in my account. 
Could you elaborate on the cases? I mean new branches for what cases? @aarmey

**Comment by aarmey** [comment]
I really don't think this is a version issue.

**Comment by aarmey** [comment]
What did the cell above this one show for fitness? I really, really don't think this is a version issue—it's much more likely something didn't get copied over. I made changes in quite a few files, and "adaptive_de_rand_1_bin_radiuslimited" is a random fitting process.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/63125488-9c361100-bf62-11e9-9fae-09c08773ba34.png)

I changed the files based on the commits

**Comment by Farnazmdi** [comment]
@aarmey  could you please run the `hill.ipynb` in your local?
I checkout in your branch `asm-fix-bbopt` and ran it, the above image was the result.

**Comment by aarmey** [comment]
Huh... have you run Pkg.update()? I get the lower error (~6E5)

**Comment by Farnazmdi** [comment]
No, I just did `]up` in Julia command line

**Comment by aarmey** [comment]
Did you restart your kernel?

**Comment by Farnazmdi** [comment]
Yes, I always do restart and run all the cells.

**Comment by Farnazmdi** [comment]
Did you get the same result as before?

**Comment by aarmey** [comment]
Yep. You could delete your `~/.julia` folder to get rid of any caches...

**Comment by Farnazmdi** [comment]
Ah, sorry I took your time for this.
So after deleting `~/.julia` I should add all the packages again, right?

**Comment by aarmey** [comment]
Yep

**Comment by Farnazmdi** [comment]
Thanks.
