### ISSUE TITLE
LabelledArrays.jl for parameter vectors?

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#164]
This might make it easier to refer to specific indices in the parameter vectors.

https://github.com/JuliaDiffEq/LabelledArrays.jl

**Comment by Farnazmdi** [comment]
@aarmey except for this issue (I will commit today in a branch) is there any other part that we want to add to the model?
I mean is there any other thing you want me to do for that paper?

**Comment by aarmey** [comment]
Do you have drug combination predictions? We'll need to have those.

**Comment by Farnazmdi** [comment]
#171
