### ISSUE TITLE
Build the model assuming we only have the first 48 hours

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#182]

**Comment by Farnazmdi** [comment]
The first 48 hours didn't seem to be accurate enough. Here are the temporal simulations for all drugs:
This is the combination:
![image](https://user-images.githubusercontent.com/34812750/76784458-eb4e5980-6770-11ea-84a2-72a85b3f489a.png)

Lapatinib:
![image](https://user-images.githubusercontent.com/34812750/76784479-f43f2b00-6770-11ea-9154-d339b6ee2c90.png)

doxorubicin:
![image](https://user-images.githubusercontent.com/34812750/76784509-03be7400-6771-11ea-9f51-5971863b064c.png)

gemcitabine:
![image](https://user-images.githubusercontent.com/34812750/76784526-0c16af00-6771-11ea-8651-c5b6463e8459.png)

paclitaxel:
![image](https://user-images.githubusercontent.com/34812750/76784554-15078080-6771-11ea-8b99-d756ac1d73b9.png)

There is no assertion error with this set of parameters, but it seemed that the predictions are not the best. So I tried with 72 hours.

**Comment by Farnazmdi** [comment]
With 72 hours it looked like it is fitting a lot better, but one assertion for combined drugs (dox and lapatinib) failed. Now I am running it for more iterations to hopefully avoid this.

**Comment by Farnazmdi** [comment]
#187

**Comment by aarmey** [comment]
Ok, good to know. Whatever the result for 72 hrs this will be helpful information for the Heiser lab to design experiments.

**Comment by Farnazmdi** [comment]
I guess it will take around 2-3 hours for 50000 iterations. Whatever the results will be, I will send along with the email to them in the afternoon.
