### ISSUE TITLE
Bliss for cell # compare to Bliss for params

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#186]

**Comment by Farnazmdi** [comment]
Just one question. The cell number should be from the experiment or the simulations? @aarmey

**Comment by aarmey** [comment]
Hmm... I guess we can just use the experiment itself.

**Comment by Farnazmdi** [comment]
Should I do some processing for it to be in fractional decrease?
Because the cell # versus concentration at T=72hrs is already decreasing. But when I calculate Bliss for them, the numbers go really high.

**Comment by aarmey** [comment]
It should be fractional decrease compared to the control at 72 hrs, not over time.

What numbers go really high?

In general, more information will be helpful to understand what you've done.

**Comment by Farnazmdi** [comment]
Sorry, of course. 
Actually, I did that, too. I will make a PR and explain there.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/76918578-e0d0b480-6883-11ea-9426-38b6cfb38f4e.png)

There is quite a difference at first concentrations.

**Comment by aarmey** [comment]
But this doesn't match the model/data comparison in the notebooks at all? Why would this be different from the agreement we see in the plots over time for no drug?

**Comment by Farnazmdi** [comment]
Sorry, my bad. I was dividing the time in the simulation into 200 points, and the original data had 192. Long story short, it was my mistake, they match quite well.

![image](https://user-images.githubusercontent.com/34812750/77232085-2fb86b80-6b5c-11ea-855f-147a4acc2558.png)
I guess I had this mistake in the other issue. I'll correct it right away.

**Comment by Farnazmdi** [comment]
#189
