### ISSUE TITLE
Write the framework for multiple replicates 

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#223]
Is the way to do this, fitting all the replicates separately and finding the lower and upper bound? @aarmey

**Comment by aarmey** [comment]
First, could you plot the three replicates on top of each other for one drug (doesn't even need to be done in code)? It'll help to see how the three replicates vary.

**Comment by Farnazmdi** [comment]
lapatinib
![image](https://user-images.githubusercontent.com/34812750/78947861-77efed00-7a7b-11ea-9058-db44a51964ef.png)

**Comment by aarmey** [comment]
Ok, these are quite close so I think you can plot mean with stderr. For fitting, it's best to fit each replicate separately (say, replicate 1 of all drugs, then separately fit replicate 2 of all drugs, ...).

http://docs.juliaplots.org/latest/generated/gr/#gr-ref37-1

**Comment by Farnazmdi** [comment]
Thanks.

**Comment by Farnazmdi** [comment]
@aarmey do you know if the data we had is different from what Dr. Gross sent, or it is one of these trials?

**Comment by aarmey** [comment]
I don't know.

**Comment by Farnazmdi** [comment]
We don't have the population data. I was trying to figure out a way to calculate the cell number from percentage without it, but I guess I can't. I will email Dr. Gross to ask for it.

**Comment by Farnazmdi** [comment]
#236
