### ISSUE TITLE
Set tau's from rate parameters

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#23]
Can tau's be set from α, β, since we know that the delay arises from the gamma distribution? I'm thinking this must be the case, but will look for some supporting literature. At the very least, we should be able to say the delay is proportional to the corresponding rate (making one delay parameter for all the concentrations).

**Comment by aarmey** [comment]
Ok, there's not really a 1:1 relationship between waiting time distribution and DDE, because there is a *distribution* of waiting times, while a DDE essentially creates one. However, we can make gamma1 and gamma2 proportional to 1/alpha and 1/beta, respectively. This gets rid of all the gamma parameters but 1. Roughly, this restricts the shape parameter of the gamma distribution to one value throughout the experiment, but this is a really reasonable assumption.

**Comment by Farnazmdi** [comment]
Sorry, I am a little confused, the gamma you are mentioning here, is it the death rate in the DDE model? or distribution for delays (or just the cells' lifetime) that are gamma-distributed?
As I understand, the two parameters of a gamma distribution which the delays are, are proportional to the inverse of the transition rates. Is this correct?

**Comment by aarmey** [comment]
Oops—got my notation confused. I mean the delay parameters.

**Comment by Farnazmdi** [comment]
So the taus are proportional to the inverse of rate transitions? I still don't see where the role of the gamma distribution is, is it like a proof that these are proportional?

**Comment by aarmey** [comment]
Thought that the gamma distribution might provide an underlying proof, but use of DDE and the cell cycle lengths distribution aren't that closely tied together. However, the delay is *roughly* the mean of the cell cycle length distribution (which is gamma). The transition rates are roughly the rate parameter of that distribution (https://en.wikipedia.org/wiki/Gamma_distribution). So, changing the delay parameter is sort of like changing the shape of gamma. A longer delay for constant transition rate should correspond to a higher shape parameter if you were to look at the distribution of cell cycle lengths. If we say the shape is constant, then we can say the delay is proportional to 1/rate.

**Comment by aarmey** [comment]
I'm not saying the gamma distribution has to be explicitly used anywhere in the DDE. Everything above is stuff we'd cover in the paper.

**Comment by Farnazmdi** [comment]
Got it, thanks, will make the changes. 
About the G1 and G2 histograms, I made the [notebook ](https://github.com/meyer-lab/DrugResponseModel.jl/blob/improve/src/plots_jl.ipynb)yesterday, but that didn't show the shift due to delay in the control and the other one, I might have made some mistakes in calculating the lengths, or maybe the data was not enough. Do you think in Heiser lab they have got new single-cell data that I can use? Should I ask them?

**Comment by aarmey** [comment]
Let's just use what you have here for now, then it will be trivial to update the figure with new data.

**Comment by Farnazmdi** [comment]
@aarmey I've put `tau1 = 1/alpha` and `tau2 = 1/beta`,
it roughly works, but one quick question. Did you mean to have a coefficient there? I mean to have `tau1 = k1/alpha` and `tau2 = k2/beta`? because this way the number of parameters to be estimated will remain the same.

**Comment by aarmey** [comment]
`tau1 = k1/alpha` and `tau2 = k1/beta`. Also, I think this further reduces things when you get to the Hill model?

**Comment by Farnazmdi** [comment]
Oh, thanks. Yes, in the hill we just will have 8 parameters!

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/63456727-6c748680-c404-11e9-9b0b-fbbe85f9ac39.png)
This is the fit I get after doing the Hill optimization. This is for one of the concentrations.

**Comment by aarmey** [comment]
Think we really have to look at all the concentrations plotted to see what the model is doing...

**Comment by Farnazmdi** [comment]
I just committed all of them,
[here](https://github.com/meyer-lab/DrugResponseModel.jl/blob/a80162414e29eb2b27e95a3b8580d13dd4e8d590/src/DDEmodel.jl#L8) I changed the dde model and added the coef. for tau1 and alpha proportionality.
[here](https://github.com/meyer-lab/DrugResponseModel.jl/blob/a80162414e29eb2b27e95a3b8580d13dd4e8d590/src/Hill.jl#L20) in the hill model removed tau1 and tau2.
[This](https://github.com/meyer-lab/DrugResponseModel.jl/blob/improve/src/DDEmodel.ipynb) is the notebook for optimizing single concentrations 
and [this](https://github.com/meyer-lab/DrugResponseModel.jl/blob/improve/src/hill.ipynb) for the hill. 
Please let me know if you think something is wrong.

**Comment by aarmey** [comment]
Ok, doesn't work.
