### ISSUE TITLE
compare many combinations and output the difference 

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#235]

**Comment by Farnazmdi** [comment]
I guess this could be a potentially good way of representing the difference between combination using our model and the conventional way done in the literature. I used the absolute difference in cell number @aarmey : our_model/conventional_model
![image](https://user-images.githubusercontent.com/34812750/79536372-c3cf0300-8034-11ea-89b9-7e30da83053b.png)

**Comment by aarmey** [comment]
This looks great! Note that I think you still want to use the ratio of the models. It'll also be helpful to have a constant color scale to compare drug combinations.

**Comment by Farnazmdi** [comment]
#251
