### ISSUE TITLE
Smoothing the raw data

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#237]
If you'd like, you can smooth the raw data using a Savitzky-Golay filter:

https://en.wikipedia.org/wiki/Savitzky–Golay_filter

There's an implementation here:

https://github.com/meyer-lab/TAModeBLI.jl/blob/master/src/SavitzkyGolay.jl

and an example of me using it here:

https://github.com/meyer-lab/TAModeBLI.jl/blob/master/src/TAModeBLI.jl#L31

**Comment by Farnazmdi** [comment]
Of course. Thanks. I couldn't find what you are referring to in the TAMode project. Could you let me know which file it is in?

**Comment by aarmey** [comment]
Do the links not work? I might have to give you access if not.

**Comment by Farnazmdi** [comment]
I am afraid the links don't work.

**Comment by aarmey** [comment]
Ok, I think they should work now.

**Comment by Farnazmdi** [comment]
Yep, thanks.

**Comment by Farnazmdi** [comment]
#242
