### ISSUE TITLE
tests not passing, though locally they pass

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#24]
![image](https://user-images.githubusercontent.com/34812750/63323089-bdd42700-c2d9-11e9-915f-070d30bf279c.png)

Tried adding `install: travis_wait mvn install` but doesn't fix it.

**Comment by aarmey** [comment]
This should fix the build: https://github.com/meyer-lab/DrugResponseModel.jl/commit/53e85dabb9ad478ac01459c699239441790bf3c6

Adding DifferentialEquations.jl as a dependency imports a whole bunch of different packages. Building was taking longer than 10m so Travis assumed the build was hung or crashed.
