### ISSUE TITLE
Play with how we do optimization

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#246]
Could you setup a function that runs local, all drug optimization with Optim rather than with bboptim? I know it will behave poorly, given the integer steps, but I'm curious about taking another approach, where we optimize locally at every number of steps and then take the best case. I can use this function as the starting point for some exploration.

**Comment by Farnazmdi** [comment]
Sure, will do.

**Comment by Farnazmdi** [comment]
#249
