### ISSUE TITLE
Analyze hill parameters based on Fallahi et al. 

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#250]
In "metrics other than potency reveal systematic variation" mentions the specific effects of the drug on cell lines in terms of the steepness of the dose-response curve, maximum effect, along with IC50 (potency)
I guess we could have that sort of analysis.

**Comment by Farnazmdi** [comment]
@aarmey should I set up something for this? Since we have those measures I can plot each of the parameters for the drugs separately. But I am not sure if this aligns with our purpose of this model.

**Comment by aarmey** [comment]
Think you need many more drugs to do much with this, and much of what they find is because of cell heterogeneity, which we assume is negligible here.

**Comment by Farnazmdi** [comment]
Huh, got it. Thanks.
