### ISSUE TITLE
Replicate plot, but with one-drug fit

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#262]
<img width="1206" alt="Screen Shot 2020-04-21 at 7 54 25 AM" src="https://user-images.githubusercontent.com/2065146/79880860-64ab1e80-83a5-11ea-9013-da52906fea4e.png">

Could you make this plot, but with parameters from only fitting lapatinib (which is also the drug shown here)? The all-drug fitting seems to be performing worse after adding palbo (we can figure that out), and I'd like to show how well the hill model does in our funding presentation. Thanks.

**Comment by Farnazmdi** [comment]
Is there any way to simulate -- or basically do something I used to do in a notebook -- in the command line? My notebook doesn't work and for this, I have to simulate the model for the three replicates.

**Comment by Farnazmdi** [comment]
I tried adding the `DrugResponseModel` in the julia command line, but it couldn't add it. There was an error.

**Comment by Farnazmdi** [comment]
Please ignore. I did `active .` and it recognizes it.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/79915587-106f6100-83dc-11ea-8e13-3106dba68526.png)

**Comment by Farnazmdi** [comment]
#264
