### ISSUE TITLE
The parameters are estimated poorly when All drugs at once

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#266]
![image](https://user-images.githubusercontent.com/34812750/79954473-3889af00-8432-11ea-9634-cc8b9e77010e.png)

The G1 progression rate should be decreasing. *all* of the parameters are increasing in all drugs, which is clearly wrong.

**Comment by Farnazmdi** [comment]
Before adding Palbociclib, they were ok, but after that they are broke.

**Comment by Farnazmdi** [comment]
I understand why we did the all-at-once fitting. But obviously it is not representative of what we want. Would that be alright to just continue with the individual fits? Or I can decrease the number of "same" parameters and only keep the nG1 and nG2 across all drugs.
@aarmey

**Comment by aarmey** [comment]
Keeping nG1 and nG2 constant is necessary for doing anything with drug combinations, so your middle suggestion is probably best.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/81883782-f6442100-954a-11ea-952e-71603916f625.png)

**Comment by Farnazmdi** [comment]
Sorry @aarmey, could you please remind me why we must have the same nG1 and nG2 for the drugs to do the combination? I used to think it is for simplification.

**Comment by aarmey** [comment]
How would you simulate a condition with both lapatinib and dox present, with the phase numbers different?

**Comment by Farnazmdi** [comment]
Oh right.

**Comment by Farnazmdi** [comment]
Could we just leave out the Palbo? Its time-series data and its mechanism is similar to lapatinib.

**Comment by aarmey** [comment]
Are all the others estimated well without palbo? Is palbo estimated well when fit on its own? If the answer is yes to both of these questions, I'd be interested in knowing what's different about palbo...

**Comment by aarmey** [comment]
Maybe it's the higher nD1? If so, we could allow palbo to have its own nD1 value to verify.

**Comment by Farnazmdi** [comment]
I actually let all of them have their own nD1 and nD2, but still, the dose-response curves are mostly all increasing...

**Comment by Farnazmdi** [comment]
The 4 drugs without palbo used to work well, I can try and fit another 4 drugs including palbo and excluding another drug to see if they fit well or not. I guess this way we find out if the problem is actually palbo or just 5 drugs is a lot to be fit at once.

**Comment by Farnazmdi** [comment]
update: I tried both scenarios. I guess something is different from the time we didn't have palbo. Any 4-drug fitting fails (compared to what we previously had without palbo). What I mean by failing is the cost function which is almost 3 times larger than before. I will try to find what was different.

**Comment by aarmey** [comment]
What about 1-drug fitting?

**Comment by Farnazmdi** [comment]
1-drug fitting works great.

**Comment by Farnazmdi** [comment]
It might sound not reasonable, but could we somehow get an average of nG1 and nG2 for the two drugs we want to combine?

**Comment by aarmey** [comment]
Seems like a hack. We can go to fitting all the drugs separately, but in one fitting process, then try and merge them one step at a time (e.g. shared nG1, then shared nG2...)

**Comment by Farnazmdi** [comment]
Could you please elaborate on how to "merge them one step at a time"?
First, I fit them separately but in one process, then I didn't get what to do.

**Comment by aarmey** [comment]
You could take your merged fit but allow all drugs to be separate. Then, once that works, start to merge things again.

**Comment by Farnazmdi** [comment]
Got it. Will do.

**Comment by Farnazmdi** [comment]
I tried the merged fit with all drugs having their own parameters, but still, something is wrong. What  I'm suspicious about is when I replaced the content of `residHillAll` function with `residHill`. I remember it was a repeated code, but I might have done something wrong when doing that. Do you think it is very inefficient if I bring that function back? I can give it a shot to see if that is the problem or not.

**Comment by aarmey** [comment]
I agree there's probably an error somewhere, but wouldn't the old approach duplicate more code? Perhaps there's a better way to test the code. For example, what happens if you fit six drugs, but they are all lapatinib?

**Comment by Farnazmdi** [comment]
It would duplicate more code. Sure, will try that. Thanks.

**Comment by Farnazmdi** [comment]
I tried it, if all drugs were lapatinib, all will be estimated wrong!

**Comment by aarmey** [comment]
So there's a code error somewhere.
