### ISSUE TITLE
compare temporal combinations

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#270]
Write a function to calculate the difference between an awful lot of time-combinations and show which one is different with the reference.

**Comment by Farnazmdi** [comment]
Looks like any combination with taxol, the order of treatment matters.

**Comment by Farnazmdi** [comment]
Have an idea that could potentially be used for sequential treatment, I guess.

What if we consider each drug treatment a state, and the cell number after that drug treatment the observation. In the framework of the tHMM, could we use this to decide which drugs could potentially be scheduled one after another? I understand the "for how long" would be a little challenging, but in the current setting we have the duration of time and the number of generations that the states persist.
Do you think this is a reasonable approach @aarmey ?

**Comment by aarmey** [comment]
What is the tree then?

**Comment by Farnazmdi** [comment]
My mistake, sorry. Just the HMM.

**Comment by aarmey** [comment]
I'm not sure I see the value over running the model we have.

**Comment by Farnazmdi** [comment]
First, I was thinking in terms of a tHMM with including single-cell fates as another observation and the time duration that a state exists until it switches to another. But I guess with the drugs being different states, then there shouldn't be any tree structure. Just the idea of state switching, I guess.
And that Single-drug effects could be used from the ODE model to give the state distributions. 
Does it make sense at all?
