### ISSUE TITLE
Methods section

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#279]
As I think the core more is essentially final, I think you should be able to write a methods section for the model at this point. This could either go in a markdown file within the repo or in the Google Doc.

**Comment by Farnazmdi** [comment]
Does it matter how it is organized? I mean the structure of it, should it be in a specific format?

**Comment by aarmey** [comment]
Methods sections don't generally adhere to many journal guidelines.

**Comment by Farnazmdi** [comment]
[Google drive link](https://docs.google.com/document/d/1HMEnI4JuwpwbI-9BDZ9pBzF-_tVNZQcEs4ZyGoYnkmM/edit?usp=sharing)

**Comment by Farnazmdi** [comment]
I moved them to the draft we had before. If you could write the titles for each sub-section, I will start to fill them out.

**Comment by aarmey** [comment]
Done.

**Comment by Farnazmdi** [comment]
Should I write for the results?

**Comment by aarmey** [comment]
Think we'd need to coordinate that with the Heiser lab.

**Comment by Farnazmdi** [comment]
Sure. How about we set a meeting with them for the next week or so? I will figure out and finish the other issue we have until then.

**Comment by Farnazmdi** [comment]
I added the part related to Loewe. Is there other topics I should add to the methods @aarmey ?

**Comment by aarmey** [comment]
None come to mind. I plan to email Dr. Heiser tomorrow to ask about making progress on this manuscript.

**Comment by Farnazmdi** [comment]
#379
