### ISSUE TITLE
Replace Bliss with Loewe

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#284]
Here is what I think is going on:
G1 and G2 progression rates in some cases are increasing with increasing concentrations (which is not necessarily an "anti-cancer" effect) and in some cases decreasing (which _is_ an anticancer effect).
For _all_ G1 and G2 progression rates, I am subtracting the control condition parameter from all others in order to put them in a decreasing order -- which is not entirely correct, I guess.
First, they still need to be normalized to be between 0 and 1;
second, for those cases that the behavior of the dose-response curve is actually decreasing, this shouldn't be done, because they are already in decreasing order.

Here is what I think I should do:
write a function that for a parameter of two drugs:
1. checks whether they both are in decreasing order,
2. if not, subtract the control condition from other parameters, and add the difference between the control condition and the highest concentration parameter to all of them (to just shift it up so that they are positive values).
3. find the minRange = min(range of both drugs) & maxRange = max(range of both drugs) and normalize the two drugs to be between 0 and 1 based on this -- this way, we are not normalizing the two parameters separately, so the scale will be preserved.
4. calculate the Bliss for these two converted and scaled parameter sets
5. convert the combined values back to the original scales.
6. done

Does this make sense to you @aarmey ? Especially the part that we shift the parameters upwards just to be positive values in step 2?

**Comment by Farnazmdi** [comment]
But I guess anti-cancer effect could also be inhibition rate (which is increasing with increasing concentrations). If true, I guess we might only need to normalize the two effects and ignore step 1 and 2.

**Comment by aarmey** [comment]
If you subtract off the control, wouldn't the cases where progression rate increases still be increasing?

You definitely *don't* want #3, because 0 should be special and indicate the drug has no effect. You want to rescale such that positive values 0–1 indicate proportional decreases in progression rate, and then the cases where a drug increases progression rate correspond to negative values.

**Comment by aarmey** [comment]
If all this scaling is becoming confusing, perhaps it might just be easier to deal with Lowe additivity? [With that, you just need a dose-response curve in an invertible functional form.](https://en.wikipedia.org/wiki/Loewe_additivity) You then can find the magnitude of the combination effect by root finding.

@stephendl102 happens to be thinking about this for the Fc project, so there might be an opportunity to reuse some effort.

**Comment by Farnazmdi** [comment]
> If you subtract off the control, wouldn't the cases where progression rate increases still be increasing?

Sorry, I meant subtracting other parameters from the control.

> You definitely don't want #3, because 0 should be special and indicate the drug has no effect. You want to rescale such that positive values 0–1 indicate proportional decreases in progression rate, and then the cases where a drug increases progression rate correspond to negative values.

Sure, I didn't notice that, just wanted to preserve their scales. 
I will try Loewe then. I will contact @stephendl102.
Thank you,

**Comment by aarmey** [comment]
I also was thinking you meant subtracting the parameters from the control, so I'm still not sure I understand?

**Comment by Farnazmdi** [comment]
Oh sorry, I missed this.
Here is what I meant:
![image](https://user-images.githubusercontent.com/34812750/82391395-0601b080-99f6-11ea-85a6-b224c7f2d41e.png)

**Comment by Farnazmdi** [comment]
I guess it is for the best to switch to Loewe. I will work on it this week.

**Comment by Farnazmdi** [comment]
Here is my progress so far:
(1) We have a function that calculates the inverse of Hill; ie., given parameters [EC50, min, max, steepness] and the effect, it returns the concentration.
(2) the combined effect is calculated by finding the root of the Loewe combination index formula.
The problem is that it cannot find any real root and asks to use complex numbers.
![image](https://user-images.githubusercontent.com/34812750/82511306-ce603a80-9ac1-11ea-89d3-756d4c12030b.png)

**Comment by aarmey** [comment]
How are you finding the root? nlsolve?

**Comment by Farnazmdi** [comment]
My bad, I had a mistake in mathematics!!
I am using `fziro()` from Roots package.
It seems working, I will update the PR as soon as I make sure it is no wrong.

**Comment by Farnazmdi** [comment]
Actually, the hill function we used is a bit different from the usual one that people use. 
The one we have in the code and are using to fit the parameters has EC50 and concentration in an inverse form. I mean we have:
![image](https://user-images.githubusercontent.com/34812750/82521363-50a92880-9adb-11ea-9ae5-6123335cc8c8.png)

And what others have is:
![image](https://user-images.githubusercontent.com/34812750/82521373-5e5eae00-9adb-11ea-8ba5-b10f8bb78718.png)

I know that if we replace the k with -k, they are the same, but could you please confirm that the bounds we are using for estimating k (positive values) are actually the correct choice?

**Comment by aarmey** [comment]
Isn't concentration on the bottom with positive Hill coefficients here?

https://en.wikipedia.org/wiki/Hill_equation_(biochemistry)

**Comment by Farnazmdi** [comment]
Yes, thanks. I saw that in this paper:
[1](https://www.biorxiv.org/content/10.1101/161059v1.full.pdf)
But still I get an error regarding complex numbers.

**Comment by Farnazmdi** [comment]
Sorry, one question. Does the following sentence mean that two curves both have to be increasing or both have to be decreasing?
![image](https://user-images.githubusercontent.com/34812750/82522529-961b2500-9ade-11ea-9262-e4f160b3f1a9.png)
Is it a constraint for Loewe?

**Comment by aarmey** [comment]
No, they can go in opposite directions.
