### ISSUE TITLE
new plots for Heiser lab

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#296]
1. Plot all the concentrations in one plot like the one Dr. Heiser wanted.
2. Fit the model to replicate averages.
3. Plot sum of squared error for each drug (?)

@aarmey Are these all the plots we have to send to Dr. Heiser?

**Comment by Farnazmdi** [comment]
One more question, for (1) should I plot the average of the three simulated replicates?

**Comment by aarmey** [comment]
I think those are the plots. Re your follow-up question, yes, the idea would be to only use the experimental average throughout.

**Comment by Farnazmdi** [comment]
#298
