### ISSUE TITLE
the error with the opimization

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#31]
@aarmey  Dr. Meyer, I changed the DDE so it would estimation at once. I made a residual function, [here](https://github.com/meyer-lab/DrugResponseModel.jl/blob/e0f9764a6451878887831f60f44df6f992f563a4/src/DDEmodel.jl#L58) in a .jl file, 
the last step that is the `bboptimize(cost_function,...)` has a weird error. Could you please take a look at it whenever convenient? it is in [this notebook](https://github.com/meyer-lab/DrugResponseModel.jl/blob/star-tau/src/DDEmodel.ipynb).
I first tried with the `bboptim`, it had this error, in the current commit I tried local optimization with `optimize()` to see if it works, and it has the same error.

**Comment by aarmey** [comment]
There are thousands of lines changed on this branch, each of which could be causing the problem. Please split all these changes up, then lets individually move them over to master in a PR. This will help isolate the problem. A good rule of thumb is 1 branch = 1 defined change. It's not unreasonable to have PR's with 2-20 lines changed.

**Comment by Farnazmdi** [comment]
I created another branch and added the functions to change the dde model to estimate the parameters for the concentrations all at once. The only files changed are the `DDEmodel.jl` and the `DDEmodel.ipynb`, the first one is [here](https://github.com/meyer-lab/DrugResponseModel.jl/blob/532a3e8c120da5f4c933e26bfd22ba73a9d39ae0/src/DDEmodel.jl#L58) which includes another `DDEsolver`, another `cost function`, and another `optimization function`. In the notebook [here](https://github.com/meyer-lab/DrugResponseModel.jl/blob/constant-delay-dde/src/DDEmodel.ipynb) I have tested the new DDEsolver, the new cost function, which work fine, but the optimization function has this error that says:
`Something went wrong. Integrator stepped past tstops but the algorithm was dtchangeable. Please report this error.`
I searched the error and it seems they have resolved it in the previous versions of `OrdinaryDiffEq` but even when I updated the packages, I still get the same error. Could you please take a look at it whenever convenient? Should I report it to them in their Github issues? @aarmey

**Comment by aarmey** [comment]
Probably best to report, especially given they explicitly ask for it.

**Comment by aarmey** [comment]
@Farnazmdi is this fixed now?

**Comment by Farnazmdi** [comment]
Oh, I didn't try their updated package. This problem was when we wanted to estimated parameters for all the concentrations at once. 
They said they have updated their package, but not sure if this addresses our problem. 
Should I try it out again?

**Comment by aarmey** [comment]
Sure. Also, if there’s any part of this repo I can help with (I.e. any sticking points), I’ll have some time over the next week.

**Comment by Farnazmdi** [comment]
Thank you, will do.

**Comment by aarmey** [comment]
Probably not an issue anymore.
