### ISSUE TITLE
optimal combination 

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#327]
Finding the optimal concentrations for combination in each pair of drugs.

**Comment by Farnazmdi** [comment]
@aarmey is this the priority, or annotating the excel sheets based on cell states?

**Comment by aarmey** [comment]
I think we want to get this out of the way first. I need to look back at the last set of analysis we sent along. Also, I think I need to get this repo building on Github Actions?

**Comment by Farnazmdi** [comment]
Sure. Last time I checked some figures were not building for some reason. I think I have to go back and do some clean up. But I can send you the pdf reports we had before if that helps. And yes please, regarding the GitHub Actions.

**Comment by aarmey** [comment]
I *think* I've gotten the build setup, though you're right, it looks like one of the Weave documents isn't building.

**Comment by Farnazmdi** [comment]
@aarmey Have you ever been able to change the kernel in a notebook from python to julia? I mean in VScode. I have the options, but when I select Julia it just doesn't change it.
![image](https://user-images.githubusercontent.com/34812750/95003354-5b98bd00-0593-11eb-91c5-ee0a0834038b.png)

**Comment by aarmey** [comment]
You do see Julia as an option, though?

**Comment by Farnazmdi** [comment]
Yes, I even see the kernel you once made accessible with 8 threads. But when I select the julia 1.4 it tries for a few seconds and without showing any error, disappears and the kernel is still python.

**Comment by aarmey** [comment]
Julia is v1.5 now. Do you have a kernel for that version? If not I'd suggest reinstalling and building IJulia.

**Comment by Farnazmdi** [comment]
It doesn’t show that. I will reinstall it then. Thank you very much

**Comment by Farnazmdi** [comment]
#342
