### ISSUE TITLE
Improve optimization

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#344]
In anticipation of dealing with multiple states, etc, we should move back to gradient-based optimization. Zygote now can handle matrix exponentials, so we should be able to do this efficiently. To make this global, there is now a package to help with multi-start methods:

https://github.com/tpapp/MultistartOptimization.jl

Probably a first step would be to take the Zygote gradient of one of the cost functions, and see what sort of errors you get. There's usually a couple adjustments needed for this.

**Comment by Farnazmdi** [comment]
I'm a little behind the schedule. I will do this as soon as I get other things done on the list. Thank you.

**Comment by aarmey** [comment]
No problem. There’s no reason to tackle this anytime soon.
