### ISSUE TITLE
Separate some code into another repo

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#345]
I wonder if it might be helpful to separate part of the code into a separate repository. Perhaps the cleanest separation would be to put the core model into another repo, with just `predict()` exposed for use? I'm open to other ideas, too.

**Comment by Farnazmdi** [comment]
Sorry, I hadn't seen this. How is this helpful?

**Comment by aarmey** [comment]
Potentially cleaner. No need to do it right now.
