### ISSUE TITLE
What do we need to make combination predictions?

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#357]
There is abundant data on the cell # effects of drugs across panels of cell lines. That's obviously not enough to predict the cell cycle-specific responses. What is the minimal information we can use to make a prediction?

(Just making an issue for this to take it off my TODO list.)

**Comment by Farnazmdi** [comment]
For calculating the sensitivity of the difference between the `bliss_model` and the `bliss_data` that we talked about:
Each drug has its own parameter (e.g., `G1_prog_rate {drugA}`, `G1_prog_rate {drugB}`). When we change the parameter to see how the difference changes, I assume we keep all the parameters along with `G1_prog_rate` for one of the drugs constant and vary the other, but then how should we accumulate the information to say this happens for `G1_prog_rate`? I mean, for each pair of concentrations we will have a 3D plane (x_axis: G1_prog_rate{drugA}, y_axis: G1_prog_rate{drugB}, z_axis: model - data).

**Comment by aarmey** [comment]
First, build a function that uses the cell cycle model to calculate the number of cells for drug 1 alone, drug 2 alone, and the combination using Bliss additivity of the cell numbers.

Second, calculate the difference between function 1 and the simulated combination of these two drugs.

Third, look at the partial derivatives of this second function.

**Comment by aarmey** [comment]
There is no `bliss_data` here. That uses the experimental data which doesn't matter.

**Comment by Farnazmdi** [comment]
Update:
I tried adding the `WebIO` package that the `Interact` needs to operate, but it seems like there is a problem with using that in VScode.
I am trying to update my Julia in anaconda (in my computer), I saw a more straight forward way of adding the package via anaconda.

**Comment by aarmey** [comment]
Yeah, you might have to run it locally.

**Comment by Farnazmdi** [comment]
Update:
I will send you a report about my analysis of the interactive notebook by the end of today.
