### ISSUE TITLE
correlation between G1 and G2

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#37]
@aarmey I thought it might be interesting to see this:
![image](https://user-images.githubusercontent.com/34812750/65284301-fee47480-daed-11e9-9b35-80497e27a4d7.png)
At first, they have a positive correlation and then it becomes negative!
These three are for lapatinib

**Comment by Farnazmdi** [comment]
This one is G1 and population
![image](https://user-images.githubusercontent.com/34812750/65284510-9d70d580-daee-11e9-910f-f8b8e61e3ec6.png)

**Comment by Farnazmdi** [comment]
And this one is G2 and population
![image](https://user-images.githubusercontent.com/34812750/65284586-d90b9f80-daee-11e9-90ac-2937a6b2517d.png)

**Comment by Farnazmdi** [comment]
Here is for doxorubicin

![image](https://user-images.githubusercontent.com/34812750/65285204-a1055c00-daf0-11e9-8baf-66f6affd9a6c.png)


![image](https://user-images.githubusercontent.com/34812750/65285231-ad89b480-daf0-11e9-9d83-81edaebe64c8.png)


![image](https://user-images.githubusercontent.com/34812750/65285240-b67a8600-daf0-11e9-93eb-72cf04e90fdd.png)

**Comment by aarmey** [comment]
The G1/G2 plots are really nice!

**Comment by Farnazmdi** [comment]
In this [paper](https://www.embopress.org/doi/full/10.15252/msb.20188604), you had sent along before, they have these plots from single-cell data with no drug treatment, and there is no correlation:
![image](https://user-images.githubusercontent.com/34812750/65285666-01e16400-daf2-11e9-94ae-60021be6adce.png)
 
This is for the single-cell data we have, time duration, lapatinib.

![image](https://user-images.githubusercontent.com/34812750/65285551-aa42f880-daf1-11e9-8b82-bc7f35362a1d.png)

![image](https://user-images.githubusercontent.com/34812750/65285566-b4fd8d80-daf1-11e9-900e-090f8f8d1a52.png)
