### ISSUE TITLE
Writing up methods description

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#379]

**Comment by Farnazmdi** [comment]
I started the methods in the [draft](https://docs.google.com/document/d/1-NSmN-wx2dsX6gZBoU4b_o0SNr53KYxLwinRL2iukyc/edit) we had with Heiserlab

**Comment by Farnazmdi** [comment]
I updated the methods part in the google doc (referenced above). Please let me know if things need to be changed. Also, I wasn't sure if we wanted to report the estimated parameters from the data (I left a comment in the google doc), and there is a part I wasn't sure if we will end up including in the manuscript which is the very last paragraph.

**Comment by aarmey** [comment]
Great. I'll go through this.

**Comment by aarmey** [comment]
Added some comments to start.
