### ISSUE TITLE
systematic error in finding control condition proportions for G1 and S/G2 phases

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#439]
@aarmey here is the function that finds the initial values. 
I may be interpreting this wrong, but I think this setting tries to balance between G1 and S/G2 initial values, and because in some drugs G1 is more than S/G2 at the initial time, it takes the middle value (50%).
In the previous setting that we didn't use steady-state condition, we were estimating one parameter (% G1 ) and just calculating %G2 = 1-%G1. I think because we are taking to account both G1 and G2 with the current setting, it tries to find a balance and it ends up being 50-50.
https://github.com/meyer-lab/DrugResponseModel.jl/blob/62ad8951269a854910926782142221761dcb2296/src/ExpODE.jl#L24

**Comment by aarmey** [comment]
@Farnazmdi have you checked before that, if you artificially set the parameters, you can get a starting percentage that is off from 50%?

**Comment by Farnazmdi** [comment]
Yes, I used a random vector for parameters, and G1 turned out to 11.2/20 and G2 =8.8/20.
I guess I was wrong.

**Comment by aarmey** [comment]
In that case I think you were right then that the optimization process is placing the starting point there.
