### ISSUE TITLE
Separate cell death EC50

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#44]
After merging this last branch, I'm curious whether you get a better fit with a separate EC50 parameter for gamma_1 and gamma_2. I think that might fix the remaining difference between the DDE and Hill performance.

**Comment by Farnazmdi** [comment]
Sure, will try it after merging this branch

**Comment by Farnazmdi** [comment]
@aarmey  this is when gamma1 and gamma2 have different EC50s, the fitness function isn't that different and it seems just a little better, 
![image](https://user-images.githubusercontent.com/34812750/65734858-ce6e7e80-e089-11e9-8cd7-d8bb3ba751bb.png)

Should I keep them the same or commit this change?

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/65734928-155c7400-e08a-11e9-9f21-0764f38f5a49.png)
This is from before, that all the EC50s were the same

**Comment by aarmey** [comment]
Yeah, doesn't look like much of an improvement. Ok, let's keep the original version.
