### ISSUE TITLE
modify cell death term in the ODE model

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/DrugResponseModel.jl#478]
@aarmey I thought a little about how to modify the death rates, but I guess if we don't want to mess with the Jacobian matrix, we should still have a "rate". Did you have a specific form of a death rate parameter in mind?
I guess if we want to make it a probability, then we need a term outside of the Jacobian matrix and it may make solving it harder?

Or did you want me to change the way we apply the Hill on death rates?

**Comment by aarmey** [comment]
Yes, you have to modify the model/Jacobian.

**Comment by aarmey** [comment]
You want to try having only one rate of progression, but then separately a probability of progression vs. death.
