### ISSUE TITLE
Plotting issue

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#54]
Something strange is happening with the plotting points for the Hill fitting.

<img width="404" alt="Screen Shot 2019-10-15 at 8 09 09 PM" src="https://user-images.githubusercontent.com/2065146/66884962-b2bf0f80-ef87-11e9-9d43-ce08acf23657.png">

**Comment by Farnazmdi** [comment]
Oh! I hadn't noticed, will look into it

**Comment by Farnazmdi** [comment]
Not sure what the problem was, but resolved in #56
