### ISSUE TITLE
Hill fitting, further improvements

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#55]
Ok, with the fix to the Hill function, we should revisit these two ideas:

- [x] First, does having a separate EC50 for the death rates significantly help the fitting
- [x] Second, does having the tau terms be constant significantly reduce the fitting performance

Specifically, I think having a separate EC50 for the death rates might allow the model to fit the oscillations for the intermediate lapatinib concentrations.

**Comment by Farnazmdi** [comment]
This is paclitaxel **after** separating the EC50 for gamma1 and gamma2 from the others 
![image](https://user-images.githubusercontent.com/34812750/66890001-4816cf80-ef99-11e9-908f-7f264fe5e025.png)

With 7000 iterations, it has 9972 fitness, doesn't look like much of an improvement.
This is the same situation for doxorubicin, fitness 18000:
![image](https://user-images.githubusercontent.com/34812750/66890956-b27d3f00-ef9c-11e9-9959-c6f8b80ee636.png)

And this is for lapatinib, fitness 15000:
![image](https://user-images.githubusercontent.com/34812750/66892152-c1b1bc00-ef9f-11e9-8b7d-771e226303af.png)

**Comment by aarmey** [comment]
Huh. I agree the fitness values seem the same, but here it looks like the model now captures the lapatinib oscillations. Is this what you see, too (not fitting oscillations with one EC50, but does fit oscillations here)?

**Comment by Farnazmdi** [comment]
Yes, I agree, the last one in trial 4 and 5 the oscillations were not captured that well. I will keep it, I'm running it with constant taus, will put the result here in a bit.

**Comment by Farnazmdi** [comment]
This is lapatinib with constant delays and different EC50s.
Could we keep the Hill for delays but report an average if it?
![image](https://user-images.githubusercontent.com/34812750/66953291-0fb3d780-f013-11e9-89de-c19e84cc9d26.png)

**Comment by aarmey** [comment]
Ok, let’s keep the separate EC50 for the death rates, and keep the Hill function for delays.

**Comment by Farnazmdi** [comment]
This is doxorubicin
![image](https://user-images.githubusercontent.com/34812750/66954974-4d662f80-f016-11e9-8ef4-c9f27b84003e.png)

**Comment by Farnazmdi** [comment]
Ok sure. Thanks.

**Comment by Farnazmdi** [comment]
One technical question! What should be a rough value for EC50? Let's say for lapatinib and doxorubicin the maximum concentration we have is 500 nM, I have set the lower and upper range for EC50 for these two to be [50.0, 250.0], and mostly it is estimated around 50.0. Do you think it is reasonable to extend the range to lower concentrations?
What about gemcitabine and paclitaxel? These two have a maximum concentration of  100.0, 15.0 nM, respectively. @aarmey

**Comment by aarmey** [comment]
Hmm... I can definitely at least say it shouldn't be beyond 10X lower or 10X higher than the minimum/maximum concentration used, respectively.

**Comment by Farnazmdi** [comment]
#56
