### ISSUE TITLE
Use global optimization

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DrugResponseModel.jl#6]
This can be done using ForwardDiff.jl. There might be a few type errors that arise, but this should work with only minor adjustments. Be sure to do this on a new branch so it’s not mixed in with other changes.

This is will make local optimization more efficient, then we can use a multi-start method for global optimization.

**Comment by Farnazmdi** [comment]
Thank you very much, I will open an issue and ask them.
[Here](http://docs.juliadiffeq.org/latest/analysis/sensitivity.html#Examples-using-ForwardDiff.jl-1) in their example with ODE they have this `convert` which as they mention is to convert the type of the varibale to be in `dual` type, I tried to do that, but probably works in another way for DDEs.
